name: Set secrets

on:
  workflow_dispatch:

jobs:
  update-secrets:
    runs-on: ubuntu-latest
    
    steps:
      - name: Install GitHub CLI
        run: sudo apt-get install gh -y

      - name: Authenticate with GitHub CLI
        run: echo "${{ secrets.GH_PAT }}" | gh auth login --with-token

      - name: Set Organization Secrets for multiple repositories
        run: |
          repos=("api-gateway" "cloud-config" "favourite-service" "infrastructure" "order-service" "payment-service" "product-service" "proxy-client" "service-discovery" "shipping-service" "user-service")
          for repo in "${repos[@]}"; do
            gh secret set DOCKER_USERNAME -b "${{ secrets.DOCKER_USERNAME }}" --repo "ecommerce-bakend/$repo"
            gh secret set DOCKER_PASSWORD -b "${{ secrets.DOCKER_PASSWORD }}" --repo "ecommerce-bakend/$repo"

          done
  